<?php
$headTitle = 'Manage Users';
$this->headTitle($headTitle);
?>
<div><?php $this->getFlashMessenger($this->flashMessenger()) ?></div>
<?php if (! $this->users) : ?>
    <h5>List is empty</h5>
<?php else : ?>
    <div class="row">
        <div class="col-sm-12">
            <h5>Users list</h5>
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Action</th>
                    </tr>
                    <?php foreach ($this->users as $user) : ?>
                        <tr>
                            <td><?= (int)++$this->productsCnt ?></td>
                            <td><?= $this->escapeHtml($user->getName()) ?></td>
                            <td><?= $this->escapeHtml($user->getEmail()) ?></td>
                            <td><?= $this->escapeHtml($user->getRole()) ?></td>
                            <td>
                                <a href="<?= $this->url('admin/users', ['action' => 'edit', 'id' => (int)$user->getId()]) ?>">
                                    Edit
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
    <br>
    <br>
    <?php
    echo $this->paginationControl(
        $this->users,
        'sliding',
        'partial/paginator',
        ['route' => 'admin/users']
    );
    ?>
<?php endif; ?>
