<?php
    echo $this->headStyle()->appendStyle('
        .portfolio { border: 1px solid #ddd; padding: 10px; border-radius: 3px; }
        .portfolio:hover { border: 1px solid #999; }
    ');
?>
<?php
$headTitle = 'Portfolio';
$this->headTitle($headTitle);
?>
<br>
<div class="row">
    <div class="col-sm-6">
        <div class="portfolio">
            <a href="http://simplesite.96.lt" target="_blank" title="Simplesite" data-toggle="tooltip" data-placement="bottom">
                <img src="/img/portfolio/simplesite.png"
                     alt="site-image"
                     width="100%"
                     height="100%"
                     class="img-responsive"
                >
            </a>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="portfolio">
            <a href="http://socnetwork.96.lt" target="_blank" title="Socnetwork" data-toggle="tooltip" data-placement="bottom">
                <img src="/img/portfolio/socnetwork.png"
                     alt="site-image"
                     width="100%"
                     height="100%"
                     class="img-responsive"
                >
            </a>
        </div>
    </div>
</div>
