<?= $this->headStyle()->appendStyle('.portfolio { border: 1px solid #ddd; padding: 10px; border-radius: 3px }'); ?>
<?php
$headTitle = 'Portfolio';
$this->headTitle($headTitle);
?>
<br>
<div class="row">
    <div class="col-sm-6">
        <div class="portfolio">
            <a href="http://simplesite.96.lt" target="_blank">
                <img src="/img/portfolio/simplesite.png"
                     alt="site-image"
                     width="100%"
                     height="100%"
                     class="img-responsive"
                >
            </a>
        </div>
    </div>
</div>
