<?php
$headTitle = $this->category->getName();
$this->headTitle($headTitle);
?>
<br>
<?php if (! is_object($this->products) || count($this->products) == 0) : ?>
    <h5>Category is empty</h5>
<?php else : ?>
    <div class="row">
        <?php foreach ($this->products as $product) : ?>
            <div class="col-xs-6 col-sm-3 items-panel">
                <div class="panel">
                    <div class="panel-body text-center img-box">
                        <div>
                            <?php if ($product->getIsNew() == 1) : ?>
                                <img src="/img/home/new.png" class="img-responsive newHomePage" alt="new">
                            <?php endif; ?>
                            <img src="<?= $this->getImage($this, $product->getImage()) ?>" class="img-responsive" alt="product-image">
                        </div>
                    </div>
                    <h5 class="panel-title text-center">
                        <a href="/product/<?= $this->escapeHtml($product->getId()) ?>">
                            <?= $this->cutStr($this->escapeHtml($product->getName()), 13) ?>
                        </a>
                    </h5>
                    <div class="panel-footer">
                        <span>Price $<?= $this->escapeHtml($product->getPrice()) ?></span>
                        <span class="pull-right add-to-cart-box">
                            <a href="#"
                               class="add-to-cart"
                               data-id="<?= (int)$product->getId()?>"
                               data-identity="<?= $this->identity() ? 'true' : 'false'; ?>"
                            >
                                Add to cart
                            </a>
                        </span>
                        <strong id="sign-in-obligatory" class="color-red"></strong>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <br>
    <br>
    <?php
    echo $this->paginationControl(
        $this->products,
        'sliding',
        'partial/paginatorForCategoryPage.phtml',
        ['route' => 'category']
    );
    ?>
<?php endif; ?>
