<?= $this->doctype() ?>
<?php $user = $this->identity() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle() ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/menu-accordion.css'))
            ->prependStylesheet($this->basePath('css/jquery-filestyle.min.css'))
            ->prependStylesheet($this->basePath('css/liMenuVert.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/paper-bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/app-script.js'))
            ->prependFile($this->basePath('js/jquery-filestyle.min.js'))
            ->prependFile($this->basePath('js/menu-accordion.js'))
            ->prependFile($this->basePath('js/jquery.liMenuVert.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <span class="need-help">
                        <strong>Need help?</strong> call us <strong class="color-red">1-10-23456789</strong>
                    </span>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <?php if ($user) : ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    <span>Hi&nbsp;<strong><?= $this->cutString($user->getName()) ?></strong></span>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="/order">My orders</a></li>
                                    <li class="divider"></li>
                                    <li><a href="/logout"><span class="fa fa-sign-out"></span> Logout</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="/basket">
                                    <i class="fa fa-shopping-basket app-basket" aria-hidden="true"></i>
                                    <span class="badge badge-basket">0</span>
                                </a>
                            </li>
                        <?php else : ?>
                            <li><a href="/register"><span class="fa fa-user-plus"></span> Sign Up</a></li>
                            <li><a href="/login"><span class="fa fa-sign-in"></span> Login</a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="logo-block">
                    <div class="col-xs-6">
                        <a href="<?= $this->url('home') ?>">
                            <img src="<?= $this->basePath() . '/img/logo.png' ?>" alt="Joke Shop" class="img-responsive">
                        </a>
                    </div>
                    <div class="col-xs-6">
                        <strong class="pull-right welcome">Welcome to the Admin area!</strong>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="title-render">
                <div class="row">
                    <div class="col-xs-6">
                        <h1 class="h1"><?= $this->headTitle()->renderTitle() ?></h1>
                    </div>
                    <div class="col-xs-6">
                        <div class="breadcrumbs-block pull-right">
                            <?= $this->navigation('navigation')->breadcrumbs()->setMinDepth(1)->setPartial('partial/breadcrumb') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="container">
            <?= $this->content ?>
        </div>
        <footer class="footer">
            <hr>
            <div class="container">
                <p>&copy; <?= $this->getYear() ?> by PHP-User. All rights reserved.</p>
            </div>
        </footer>
        <?= $this->inlineScript() ?>

        <a id="back-to-top"
           href="#"
           class="btn btn-primary btn-md back-to-top"
           role="button"
           data-toggle="tooltip"
           data-placement="left">
            <span class="glyphicon glyphicon-chevron-up"></span>
        </a>
    </body>
</html>
