<?php
$headTitle = 'Edit Admin';
$this->headTitle($headTitle);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/admins', ['action' => 'edit', 'id' => $this->id]));
$form->prepare();

$role = $this->escapeHtml($form->get('role')->getValue());
$name = $this->escapeHtml($form->get('name')->getValue());
$submit = $form->get('submit')->setValue('Edit ' . $role);
?>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h5 class="modal-title" id="myModalLabel">Are You sure?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" id="delete-admin">Yes</button>
            </div>
        </div>
    </div>
</div>
<!-- Hidden form for delete admin -->
<form action="<?= $this->url('admin/admins', ['action' => 'delete', 'id' => $this->id]) ?>"
      method="post"
      class="delete-admin-form"
>
    <button type="button">Yes</button>
</form>
<br>
<div class="row">
    <div class="col-sm-12">
        <div><strong>Name: </strong>&nbsp;&nbsp;<?= $name ?></div>
        <?= $this->form()->openTag($form) ?>
        <div class="form-group">
            <div class="col-sm-12">
                <strong>Role:</strong>&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="radio-box">
                    <?= $this->formRadio($form->get('role')) ?>
                </span>
            </div>
        </div>
        <?= $this->formSubmit($form->get('submit')) ?>
        <?= $this->form()->closeTag() ?>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-12">
        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
            Delete <?= $role ?>
        </button>
    </div>
</div>
