<?php
$headTitle = 'Manage Admins';
$this->headTitle($headTitle);
?>
<?php if (! $this->admins) : ?>
    <h5>List is empty</h5>
<?php else : ?>
    <div class="row">
        <div class="col-sm-12">
            <div><?php $this->getFlashMessenger($this->flashMessenger()) ?></div>
            <h5>Admins list</h5>
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Action</th>
                    </tr>
                    <?php foreach ($this->admins as $admin) : ?>
                        <tr>
                            <td>#</td>
                            <td><?= $this->escapeHtml($admin->getName()) ?></td>
                            <td><?= $this->escapeHtml($admin->getEmail()) ?></td>
                            <td><?= $this->escapeHtml($admin->getRole()) ?></td>
                            <td>
                                <a href="<?= $this->url('admin/admins', ['action' => 'edit', 'id' => (int)$admin->getId()]) ?>">
                                    Edit
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>