<?php
$headTitle = 'Basket';
$this->headTitle($headTitle);
?>
<?php if (! $this->products) : ?>
<h6><em>You didn't select any product. Basket is empty.</em></h6>
<?php else : ?>
<h6 class="h6-basket-selected-products"><em>Selected product(s)</em></h6>
<div class="table-responsive">
    <table class="table table-hover table-striped">
        <tr>
            <th>Product name</th>
            <th>Image</th>
            <th>Price</th>
            <th>Amount</th>
            <th>Quantity</th>
            <th>Action</th>
        </tr>
        <?php foreach ($this->products as $product) : ?>
        <tr>
            <td>
                <a href="/product/<?= (int)$product->getId() ?>">
                    <?= $this->cutStr($this->escapeHtml($product->getName()), 13) ?>
                </a>
            </td>
            <td>
                <img src="<?= $this->escapeHtml($product->getImage()) ?>" width="30px" height="30px">
            </td>
            <td>US $<?= $this->escapeHtml($product->getPrice()) ?></td>
            <td class="basket-price">US $
                <span>
                    <?= number_format($this->escapeHtml($product->getPrice()) * $this->productsSession[(int)$product->getId()], 2) ?>
                </span>
            </td>
            <td>
                <ul class="plus-minus-product list-unstyled list-inline">
                    <li>
                        <a href="#" class="add-to-cart" data-id="<?= (int)$product->getId() ?>">
                            <span class="badge"><i class="fa fa-plus" aria-hidden="true"></i></span>
                        </a>
                    </li>
                    <li>
                        <span class="basket-concrete-product-count">
                            <?= $this->productsSession[(int)$product->getId()] ?>
                        </span>
                    </li>
                    <li>
                        <a href="#" class="subtract-from-cart" data-id="<?= (int)$product->getId() ?>">
                            <span class="badge"><i class="fa fa-minus" aria-hidden="true"></i></span>
                        </a>
                    </li>
                </ul>
            </td>
            </td>
            <td>
                <form action="<?= $this->url('basket', ['action' => 'delete', 'id' => (int)$product->getId()]) ?>"
                      method="post"
                      class="form-delete-button delete-concrete-product"
                >
                    <i class="glyphicon glyphicon-trash"></i>
                    <button>Delete</button>
                </form>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<br>
<div>
    <strong>Total count:</strong>
    <strong  class="selected-product-total-count color-red"><?= $this->totalCount ?></strong>
</div>
<div>
    <strong>Total price:</strong> US $
    <strong  class="total-price color-red"><?= number_format($this->totalPrice, 2) ?></strong>
</div>
<hr>
<div class="row basket-continue-cancel-buttons-box">
    <div class="col-sm-6">
        <a href="<?= $this->url('order', ['action' => 'add']) ?>" class="btn btn-primary">Continue</a>
    </div>
    <div class="col-sm-6">
        <a href="<?= $this->url('basket', ['action' => 'clear']) ?>"
           class="btn btn-danger pull-right basket-cancel-button"
        >
            Cancel
        </a>
    </div>
</div>
<?php endif; ?>
