<?php
$headTitle = 'Admin area';
$this->headTitle($headTitle);
?>
<h5>You have the following capabilities:</h5>
<ul class="list-unstyled">
    <li><a href="/admin/categories">Manage categories</a></li>
    <li><a href="/admin/products">Manage products</a></li>
    <li><a href="/admin/slider">Manage slider</a></li>
    <li><a href="/admin/users">Manage users</a></li>
    <li><a href="/admin/orders">Manage orders</a></li>
</ul>
