<?php
$headTitle = 'Add product';
$this->headTitle($headTitle);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/products', ['action' => 'add']));

foreach ($form as $element) {
    $attributes = $element->getAttributes();

    if (isset($attributes['required']) && $attributes['required'] == 'required') {
        $element->setLabel($element->getLabel() . ' *');
    }
}

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-sm-12">
        <div class="well">
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    <fieldset><legend>Fill the form please</legend><br>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('name')) ?>
                            <div class="col-sm-10">
                                <?= $this->formText($form->get('name')) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('price')) ?>
                            <div class="col-sm-10">
                                <?= $this->formText($form->get('price')) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('availability')) ?>
                            <div class="col-sm-10">
                                <?= $this->formCheckbox($form->get('availability')) ?>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>

<?= $this->form()->closeTag() ?>
