<?php
$headTitle = 'Edit product';
$this->headTitle($headTitle);

$form = $this->form;
$form->setAttribute('action', $this->url('admin/products', ['action' => 'edit', 'id' => $this->id]));
$form->prepare();

foreach ($form as $element) {
    $attributes = $element->getAttributes();

    if (isset($attributes['required']) && $attributes['required'] == 'required') {
        $element->setLabel($element->getLabel() . ' *');
    }
}
?>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h5 class="modal-title" id="myModalLabel">Are You sure?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" id="delete-product">Yes</button>
            </div>
        </div>
    </div>
</div>
<!-- Hidden form for delete user or admin -->
<form action="<?= $this->url('admin/products', ['action' => 'delete', 'id' => $this->id]) ?>"
      method="post"
      class="delete-product-form"
>
    <button type="button">Yes</button>
</form>
<div class="row">
    <div class="col-sm-12">
        <div class="well">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <?= $this->form()->openTag($form) ?>
                    <fieldset><legend>Fill the form please</legend><br>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('name')) ?>
                            <div class="col-sm-10">
                                <?= $this->formText($form->get('name')) ?>
                                <?= $this->formElementErrors($form->get('name')) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('price')) ?>
                            <div class="col-sm-10">
                                <?= $this->formText($form->get('price')) ?>
                                <?= $this->formElementErrors($form->get('price')) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('category')) ?>
                            <div class="col-sm-10">
                                <?= $this->formSelect($form->get('category')) ?>
                                <?= $this->formElementErrors($form->get('category')) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('description')) ?>
                            <div class="col-sm-10">
                                <?= $this->formTextarea($form->get('description')) ?>
                                <?= $this->formElementErrors($form->get('description')) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('availability')) ?>
                            <div class="col-sm-10">
                                <?= $this->formCheckbox($form->get('availability')) ?>
                                <?= $this->formElementErrors($form->get('availability')) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('isNew')) ?>
                            <div class="col-sm-10">
                                <?= $this->formCheckbox($form->get('isNew')) ?>
                                <?= $this->formElementErrors($form->get('isNew')) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get('status')) ?>
                            <div class="col-sm-10">
                                <?= $this->formCheckbox($form->get('status')) ?>
                                <?= $this->formElementErrors($form->get('status')) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12 col-sm-offset-2">
                                <p class="admin-product-edit-img">
                                    <img src="<?= $this->product->getImage() ?>"
                                         alt="product-picture"
                                         class="img-responsive"

                                    >
                                </p>
                            </div>
                            <?= $this->formLabel($form->get('file')) ?>
                            <div class="col-sm-10">
                                <?= $this->formFile($form->get('file')) ?>
                                <?= $this->formElementErrors($form->get('file')) ?>
                            </div>
                        </div>
                        <br>
                        <div class="form-group">
                            <div class="col-sm-12 col-sm-offset-2">
                                <?= $this->formSubmit($form->get('submit')) ?>
                            </div>
                        </div>
                    </fieldset>
                    <?= $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-12">
        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
            Delete product
        </button>
    </div>
</div>
