<?php
$headTitle = 'Manage products';
$this->headTitle($headTitle);
?>
<?php $this->getFlashMessenger($this->flashMessenger()) ?>
<div class="row">
    <div class="col-sm-6">
        <form action="<?= $this->url('admin/products') ?>" method="post" class="navbar-form navbar-left admin-product-form" role="search">
            <div class="form-group">
                <input class="form-control"
                       placeholder="Products count per home page"
                       type="text"
                       name="products_count_per_home_page"
                >
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
    <div class="col-sm-6">
        <form action="<?= $this->url('admin/products') ?>" method="post" class="navbar-form navbar-right" role="search">
            <div class="form-group">
                <input class="form-control"
                       placeholder="Products count per category page"
                       type="text"
                       name="products_count_per_category_page"
                >
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-6 col-sm-push-6">
        <div class="pull-right admin-add-product-block">
            <a href="<?= $this->url('admin/products', ['action' => 'add']) ?>" class="btn btn-default">Add product</a>
        </div>
    </div>
    <div class="col-sm-6 col-sm-pull-6">
        <form action="#"
              method="post"
              class="navbar-form admin-product-form"
              role="search"
              id="adminProductSearch"
        >
            <div class="form-group">
                <input class="form-control" placeholder="Find product" name="findProduct" type="text">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul id="adminProductSearchResult" class="list-unstyled"></ul>
    </div>
</div>
<hr>
<?php if (! is_object($this->products) || count($this->products) == 0) : ?>
    <h5>List is empty</h5>
<?php else : ?>
    <div class="row">
        <div class="col-sm-12">
            <h5>Products list</h5>
            <br>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <tr>
                        <th>#</th>
                        <th>Designation</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th>Description</th>
                        <th>Availability</th>
                        <th>Is new</th>
                        <th>Visible</th>
                        <th>Image</th>
                        <th>Action</th>
                    </tr>
                    <?php foreach ($this->products as $product) : ?>
                    <tr>
                        <td><?= (int)++$this->productsCnt ?></td>
                        <td><?= $this->escapeHtml($product->getName()) ?></td>
                        <td>US $<?= number_format($product->getPrice(), 2) ?></td>
                        <td><?= $this->escapeHtml($product->getCategory()->getName()) ?></td>
                        <td><?= $this->cutStr($this->escapeHtml($product->getDescription())) ?></td>
                        <td><?= $product->getAvailability() ? 'Available' : 'Not available'; ?></td>
                        <td><?= $product->getIsNew() ? 'Yes' : 'No'; ?></td>
                        <td><?= $product->getStatus() ? 'Yes' : 'No'; ?></td>
                        <td><img src="<?= $this->escapeHtml($product->getImage()) ?>" width="30" height="30" alt="pic"></td>
                        <td>
                            <a href="<?= $this->url('admin/products', ['action' => 'edit', 'id' => (int)$product->getId()]) ?>">
                                Edit
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
    <br>
    <br>
    <?php
    echo $this->paginationControl(
        $this->products,
        'sliding',
        'partial/paginator',
        ['route' => 'admin/products']
    );
    ?>
<?php endif; ?>
