<?php
$headTitle = 'Home';
$this->headTitle($headTitle);
?>
<br>
<div class="row">
    <div class="col-xs-6 col-sm-3 items-panel">
        <div class="panel">
            <div class="panel-body text-center">
                <img src="/img/items/1.png" class="img-responsive" alt="">
            </div>
            <h5 class="panel-title text-center">Item name sdas</h5>
            <div class="panel-footer">
                <span>Price $1000.50</span>
                <span class="pull-right"><a href="#">Add to cart</a></span>
            </div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-3 items-panel">
        <div class="panel">
            <div class="panel-body text-center">
                <img src="/img/items/2.png" class="img-responsive" alt="">
            </div>
            <h5 class="panel-title text-center">Item name</h5>
            <div class="panel-footer">
                <span>Price $10.50</span>
                <span class="pull-right"><a href="#">Add to cart</a></span>
            </div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-3 items-panel">
        <div class="panel">
            <div class="panel-body text-center">
                <img src="/img/items/1.png" class="img-responsive" alt="">
            </div>
            <h5 class="panel-title text-center">Item name</h5>
            <div class="panel-footer">
                <span>Price $10.50</span>
                <span class="pull-right"><a href="#">Add to cart</a></span>
            </div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-3 items-panel">
        <div class="panel">
            <div class="panel-body text-center">
                <img src="/img/items/2.png" class="img-responsive" alt="">
            </div>
            <h5 class="panel-title text-center">Item name</h5>
            <div class="panel-footer">
                <span>Price $10.50</span>
                <span class="pull-right"><a href="#">Add to cart</a></span>
            </div>
        </div>
    </div>
</div>