<?php
$headTitle = 'My orders';
$this->headTitle($headTitle);
?>
<br>
<?php if (! $this->userOrders) : ?>
<h5>List is empty</h5>
<?php else : ?>
<div class="row">
    <div class="col-sm-12">
    <?php foreach ($this->userOrders as $key => $order) : ?>
        <div class="my-order-top-panel">
            <h6><strong>Order date:</strong> <?= $order['userData']->getOrderDate()->format('d F Y'); ?></h6>
            <div><strong>Status:</strong> <?= $this->escapeHtml($order['userData']->getStatus()) ?></div>
        </div>
        <?php foreach ($order['productData'] as $products) : ?>
            <div class="my-order-bottom-panel">
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-3">
                        <img src="<?= $this->escapeHtml($products[0]->getImage()) ?>" class="img-responsive" alt="product">
                    </div>
                    <div class="col-lg-10 col-md-10 col-sm-9">
                        <div><strong>Product name</strong>: <?= $this->escapeHtml($products[0]->getName()) ?></div>
                        <div><strong>Price:</strong> US $<?= number_format($products[0]->getPrice(), 2) ?></div>
                        <div><strong>Count:</strong> <?= (int)$products[1] ?></div>
                        <div><strong>Total:</strong> US $<?= number_format($products[1] * $products[0]->getPrice(), 2) ?></div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        <?php if ($key != count($this->userOrders) - 1) : ?>
            <hr>
        <?php endif; ?>
    <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
